### ISSUE TITLE
Be able to use mmm-mode two levels deep

### ISSUE THREAD

**Issue by rodrigues** [purcell/mmm-mode#102]
I've originally posted this in stack exchange, but it seems more proper here.

Thanks!

https://emacs.stackexchange.com/questions/54698/can-i-use-mmm-mode-two-levels-deep

I have the following elixir code that looks like this:

```elixir
defmodule Drawing do
  use Surface.Component

  def render(assigns) do
    ~H"""
    <svg viewBox={{ "0 0 #{@width} #{@height}" }}>
      {{ SomeElixirCall.here() }}
    </svg>
    """
  end
end
```

It's elixir outside, with HTML in between `~H"""` and `"""`, and elixir inside the html, between `{{` and `}}`.

I have made some mmm config that managed to highlight the html parts and the outer elixir part, but not the elixir inside the html.

Is that possible with mmm, two levels deep mmm'ing? Or maybe I am just doing it wrong? Thanks!

```emacs-lisp
(mmm-add-classes
 '((sf-elixir
    :submode mhtml-mode
    :front "^[ ]*~H\"\"\"$" ;; regex to find the opening tag
    :back "^[ ]*\"\"\"$"))) ;; regex to find the closing tag

(mmm-add-mode-ext-class 'elixir-mode nil 'sf-elixir)

(mmm-add-classes
 '((elixir-sf
    :submode elixir-mode
    :front "{{" ;; regex to find the opening tag
    :back "}}"))) ;; regex to find the closing tag

(mmm-add-mode-ext-class 'mhtml-mode nil 'elixir-sf)
```

**Comment by dgutov** [comment]
The first argument to `mmm-add-mode-ext-class` is the primary major mode, so the last form should be:

```lisp
(mmm-add-mode-ext-class 'elixir-mode nil 'elixir-sf)
```

Unfortunately, this doesn't give the desired effect (the HTML section doesn't have the expected highlighting).

So the answer seems to be "it not supported". The fix could be trivial, though. I should look into this sometime.

**Comment by rodrigues** [comment]
@dgutov thanks a lot! I will rename the issue from a question into an enhancement request then 🙂

**Comment by dgutov** [comment]
Some fiddling later: it actually works if you add the settings for the submodes in the reverse nesting order:

```lisp
(mmm-add-classes
 '((elixir-sf
    :submode elixir-mode
    :face highlight
    :front "{{" ;; regex to find the opening tag
    :back "}}"))) ;; regex to find the closing tag

(mmm-add-mode-ext-class 'elixir-mode nil 'elixir-sf)

(mmm-add-classes
 '((sf-elixir
    :submode mhtml-mode
    :front "^[ ]*~H\"\"\"$" ;; regex to find the opening tag
    :back "^[ ]*\"\"\"$"))) ;; regex to find the closing tag

(mmm-add-mode-ext-class 'elixir-mode nil 'sf-elixir)
```

I also added `:face` setting for the inner submode, to distinguish it more easily. And pushed a small fix that seems to make syntax highlighting work more reliably.

Give it a go sometime.

**Comment by rodrigues** [comment]
Hi @dgutov !

Thanks for the suggestion, I don't think it worked well for me, maybe I'm missing something?

<img width="717" alt="Screenshot 2020-05-08 at 13 54 23" src="https://user-images.githubusercontent.com/128147/81403345-788baa00-9133-11ea-94e2-2bcb48a6ff3b.png">

That was my config

```elisp

(mmm-add-classes
 '((elixir-surface
    :submode elixir-mode
    :face highlight
    :front "{{"   ;; regex to find the opening tag
    :back "}}"))) ;; regex to find the closing tag

(mmm-add-mode-ext-class 'elixir-mode nil 'elixir-surface)

(mmm-add-classes
 '((surface-elixir
    :submode mhtml-mode
    :front "^[ ]*~[LH]\"\"\"$" ;; regex to find the opening tag
    :back "^[ ]*\"\"\"$"))) ;; regex to find the closing tag

(mmm-add-mode-ext-class 'elixir-mode nil 'surface-elixir)
```

Thanks!

**Comment by dgutov** [comment]
Did the original example work for you (it did here)? If yes, could you post the new code sample?

**Comment by rodrigues** [comment]
In the original example, the interpolation seems to kick in, but not the rest.

I've added some more syntax that don't seem to render nicely.

<img width="749" alt="Screenshot 2020-05-08 at 15 24 20" src="https://user-images.githubusercontent.com/128147/81409777-ffdf1a80-913f-11ea-91a2-dcda9529b17a.png">

**Comment by dgutov** [comment]
If you post code samples as text, I could actually try them out.

**Comment by rodrigues** [comment]
@dgutov sorry man, just saw it now:

```elixir
defmodule Drawing do
  use Surface.Component

  def render(assigns) do
    ~H"""
    <svg viewBox={{ "0 0 #{@width} #{@height}" }}>
      {{ SomeElixirCall.here() }}
      {{ :thingy }}
      {{ @module_attr }}
      {{ %{a: 1, b: "2", c: true} }}
    </svg>
    """
  end

  def comparison do
    view_box = "0 0 #{@width} #{@height}"
    SomeElixirCall.here()
    :thingy
    @module_attr
    %{a: 1, b: "2", c: true}
  end
end

```

**Comment by dgutov** [comment]
@rodrigues Hey, no problem.

But um, your example renders fine over here (with either configuration):

![Screenshot from 2020-05-21 04-28-08](https://user-images.githubusercontent.com/271877/82513414-9ede1c00-9b1b-11ea-9612-6274f078b8e6.png)

Note that you need to reopen the file after the configuration is changed.

Some further questions:

* Did you use the latest `mmm-mode` from MELPA?
* Are you using `elixir-mode`?
* Could you post the resulting values of `mmm-classes-alist` and `mmm-mode-ext-classes-alist`?
* Does anything change if you add the below to your config?

```el
(require 'mmm-defaults)

(setq mmm-global-mode 'auto
      mmm-submode-decoration-level 2
      mmm-parse-when-idle t)
```

**Comment by rodrigues** [comment]
Thanks @dgutov, I couldn't make it work here 😕

> Did you use the latest mmm-mode from MELPA?
> Are you using elixir-mode?

Yes, using elixir-mode, and all packages up-to-date 👍

> Could you post the resulting values of mmm-classes-alist and mmm-mode-ext-classes-alist?

```elisp
;; mmm-classes-alist

((universal :front "{%\\([a-zA-Z-]+\\)%}" :back "{%/~1%}" :insert
            ((47 universal "Submode: " @ "{%" str "%}" @ "
" _ "
" @ "{%/" str "%}" @))
            :match-submode mmm-univ-get-mode :save-matches 1)
 (surface-elixir :submode mhtml-mode :front "^[ ]*~[LH]\"\"\"$" :back "^[ ]*\"\"\"$")
 (elixir-surface :submode elixir-mode :front "{{" :back "}}")
 (html-css :classes
           (css-cdata css css-inline))
 (css-inline :submode css-mode :face mmm-code-submode-face :front "style=\"" :back "\"" . #1=(:private t))
 (css :submode css-mode :face mmm-code-submode-face :front "<style[^>]*>[ 	]*
?" :back "[ 	]*</style>" :insert
((99 css-tag nil @ "<style type=\"text/css\">" @ "
" _ "
" @ "</style>" @))
. #1#)
 (css-cdata :submode css-mode :face mmm-code-submode-face :front "<style[^>]*>[ 	
]*\\(//\\)?<!\\[CDATA\\[[ 	]*
?" :back "[ 	]*\\(//\\)?]]>[ 	
]*</style>" :insert
 ((99 css-tag nil @ "<style type=\"text/css\">" @ "
" _ "
" @ "</style>" @))
 . #1#))

;; mmm-mode-ext-classes-alist

((elixir-mode nil surface-elixir)
 (elixir-mode nil elixir-surface)
 (html-mode "\\.php\\'" html-php)
 (html-mode nil html-css)
 (html-mode nil html-js)
 (html-erb-mode nil html-css)
 (html-erb-mode nil html-js)
 (html-erb-mode "\\.ejs\\'" ejs)
 (html-erb-mode "\\.erb\\'" erb)
 (nxml-mode #1="\\.r?html\\(\\.erb\\)?\\'" html-css)
 (html-mode #1# html-css))
```

> Does anything change if you add the below to your config?

It changes the background, but the elixir code is still the same way:

<img width="1541" alt="Screenshot 2020-05-21 at 14 13 47" src="https://user-images.githubusercontent.com/128147/82558130-4cc5e680-9b6d-11ea-9d81-21c4edabfa21.png">

For now I've flipped the declarations, put `surface-elixir` before `elixir-surface`, html code is not highlighted, but at least elixir parts are highlighted properly. Thanks a lot!

<img width="1618" alt="Screenshot 2020-05-21 at 14 10 05" src="https://user-images.githubusercontent.com/128147/82557853-c7423680-9b6c-11ea-9d36-8fa4553f7729.png">

**Comment by dgutov** [comment]
Thank you.

Forgot to ask: what's your version of Emacs? It seems to work fine with Emacs 26.3 and 27 snapshot here.

And Emacs 25 doesn't have `mhtml-mode`.

**Comment by rodrigues** [comment]
@dgutov I'm using 26.3

**Comment by dgutov** [comment]
Could you perhaps show a repro starting with `emacs -Q`?

Like if `emacs -Q -L ~/.emacs.d/mmm-mode-12345 -l ~/.emacs.d/mmm-settings.el`, followed by visiting a file, triggers the problem, I'd like to see the contents of `mmm-settings.el`. Preferably if you can make them as small as possible.

**Comment by dgutov** [comment]
Aw damn. I know what this is about: `mmm-mode` is not in MELPA anymore. I forgot about that.

That means that having the packages up-to-date still didn't give you the latest code. Sorry about that.

**Comment by rodrigues** [comment]
No problem, thanks so much for digging into it.

I couldn't make the `emacs -Q` work, was gonna try harder sometime this weekend. But now I'll wait for the upgrade then, thanks!

**Comment by dgutov** [comment]
Release 0.5.8 should be out soon. Please test when you have the chance.

**Comment by rodrigues** [comment]
Now the highlight nesting works like a charm, thanks a lot man! 👏

<img width="913" alt="Screenshot 2020-05-25 at 11 51 25" src="https://user-images.githubusercontent.com/128147/82801743-15617d80-9e7e-11ea-8064-74ed3723d4a0.png">

I've got still a couple of issues though:

- `{{` doesn't agree with `rainbow-delimiters`, had to disable for now
- there are some html warnings also because of that `{{` not fitting well in that mode

Not sure if `mmm-mode` can or should provide some help with that. If it makes sense, I think it would be nice for the `{{` or `}}` to  be either in some sort of limbo in between these two modes, or in the `elixir-mode` side.

Something else I have no idea if it's possible: if all code in between double brackets could mean something like `""` to the `mhtml-mode` side, all syntax warnings would be gone.

Cheers!

**Comment by dgutov** [comment]
> Now the highlight nesting works like a charm, thanks a lot man! clap

Great!

As for the issues, they likely require knowledge of each particular feature, and posibly special handling in there.

Does the `rainbow-delimiters` behavior improve if you surround `{{ "0 0 #{@width} #{@height}" }}` with (extra) quotes? Will that work in the template engine used?

As for HTML validation error, which feature does this come from? If some code is sending text to an external validator, it would need to be taught to only send the right parts of the buffer.

I'm guessing you'll end up disabling it anyway, since the "missing <!DOCTYPE> declaration" seems to say this validator doesn't accept document fragments, only full documents. But maybe it has an alternative mode.

BTW: Could you tell me which theme is this? :)

**Comment by rodrigues** [comment]
the theme is `spacemacs-light` 🙂

extra quotes won't change anything for rainbow-delimiters, and it wouldn't be valid surface too. I guess I'll keep it disabled for now.

will also disable the flycheck errors for html for now, thanks for the help! 👍

**Comment by dgutov** [comment]
Regarding this:

> If it makes sense, I think it would be nice for the {{ or }} to be either in some sort of limbo in between these two modes, or in the elixir-mode side

You can "extend" the `elixir-mode` subregion by amending the definition like this:

```el
(mmm-add-classes
 '((elixir-surface
    :submode elixir-mode
    :delimiter-mode elixir-mode
    :front-delim 0
;    :front-face error
    :back-delim 0
;   :back-face error
    :front "{{"   ;; regex to find the opening tag
    :back "}}"))) ;; regex to find the closing tag
```

...but, by itself, it won't have a big effect on syntax highlighting or linting.

Things seem to be working otherwise, so: closing. And thanks for the report.

**Comment by dgutov** [comment]
> the theme is spacemacs-light slightly_smiling_face

Thanks! I've tried it and got hung up for a while on the background being different. But you probably just customized it. :-)
