### ISSUE TITLE
font-lock does not respect region boundaries

### ISSUE THREAD

**Issue by stephe-ada-guru** [purcell/mmm-mode#103]
In the attached file (renamed to add .txt)
[debug.wy.txt](https://github.com/purcell/mmm-mode/files/4733136/debug.wy.txt)
, the '%code' section is in ada-mode, the rest of the file in wisitoken-grammar-mode (both modes in GNU ELPA).

I'd like to add ?\' to the wisitoken-grammar-mode syntax table, so the various strings '{', '}' have the string face:
(modify-syntax-entry ?\' "\"" wisittoken-grammar-mode-syntax-table)

However, doing that causes almost everything after the %code section to have string face, because of the ' in the Ada code (which is an 'attribute', not a string delimiter).

Apparently syntax-ppss is running on the whole file, not just the wisitoken-grammar-mode part.

I have not tried to debug this further

**Comment by purcell** [comment]
Is a snippet of `mmm-mode` configuration necessary to reproduce this error?

**Comment by stephe-ada-guru** [comment]
Attached is a minimal mmm mode that shows the problem.

recipe:

rename debug-mode.el.txt to debug-mode.el
leave debug.wy.txt as is
emacs -Q ;; I'm using master as of 17 may
M-x (package-initialize)
M-x (load-file "~/Elisp_Work/debug-mode.el")
C-x C-f debug.wy.txt
M-x debug-mode

[debug-mode.el.txt](https://github.com/purcell/mmm-mode/files/4735176/debug-mode.el.txt)

**Comment by dgutov** [comment]
Hi Stephen,

Thanks for the full example.

It's not so much that font-lock bleeds, it's that `syntax-ppss` scans the full region. So we need to help it a little bit. For now I've added an ad-hoc solution in the shape of `mmm-after-syntax-propertize-functions` hook (you can see how it's used in `html-erb-mode`).

You example seems to work with this change:

```el
(define-derived-mode debug-mode prog-mode "Debug"
  "A major mode for Wisi grammar files."

  (setq font-lock-defaults
	'(nil ;; keywords
	  nil ;; keywords-only
	  ))

  (add-hook 'mmm-after-syntax-propertize-functions
            #'debug-mode-after-syntax-propertize))

(defun debug-mode-after-syntax-propertize (overlay _mode beg end)
  (when overlay
    (with-silent-modifications
      (funcall
       (syntax-propertize-rules ("'" (0 ".")))
       beg end))))
```

Adjust the rules at the end as necessary.

**Comment by stephe-ada-guru** [comment]
Dmitry Gutov <notifications@github.com> writes:

> It's not so much that font-lock bleeds, it's that `syntax-ppss` scans
> the full region.

Ok

> So we need to help it a little bit. For now I've added an ad-hoc
> solution in the shape of `mmm-after-syntax-propertize-functions` hook
> (you can see how it's used in `html-erb-mode`).

What's wrong with syntax-propertize-function? mmm-mode already handles
that correctly. And useing that works for my case.

-- 
-- Stephe

**Comment by dgutov** [comment]
> What's wrong with syntax-propertize-function? mmm-mode already handles
that correctly. And useing that works for my case.

It's not wrong, and it that works for you, excellent. Using `mmm-after-syntax-propertize-functions`, however, gets you access to the current mmm context, described by the arguments `mode` and `overlay`. Which might make writing the same code a tad easier.

**Comment by dgutov** [comment]
BTW, @purcell thanks for doing the triaging, here and in some other reports.

**Comment by purcell** [comment]
> BTW, @purcell thanks for doing the triaging, here and in some other reports.

All good. Happy to transfer this repo either to your Github acct or a new org if you prefer, though: you're basically doing all the maintenance at this point. Up to you, I'm fine with the status quo.

**Comment by dgutov** [comment]
@purcell If you wanted to do the transfer at some point, my acc is good. But I'm happy with the status quo as well, if it means exchanging whatever extra "fame" I might receive for occasional help like this. ;-)

**Comment by dgutov** [comment]
@stephe-ada-guru If you have any further problems, please let us know.
