### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by AlexDaniel** [purcell/mmm-mode#118]
I'm coming from [this vue-mode ticket](https://github.com/AdamNiederer/vue-mode/issues/74) because I was seeing issues in `<script>` sections of vue files. There's a suggested workaround in that ticket, but it seems like some fixes were applied in `mmm-mode` itself and the workaround is no longer needed. Last `mmm-mode` release [was in 2018](https://github.com/purcell/mmm-mode/tags), maybe it's time for a new tag?

FWIW, vue files [still seem to be broken](https://github.com/AdamNiederer/vue-mode/issues/74#issuecomment-722379204) to me, but it can be a bit hard to figure out what's the new issue if everyone is still seeing just the old one.

**Comment by AlexDaniel** [comment]
Feel free to close, I managed to [figure out the issue](https://github.com/AdamNiederer/vue-mode/issues/74#issuecomment-722483592) I had with my particular config. I don't know how versioning is done in mmm-mode so maybe there's no issue at all.

**Comment by dgutov** [comment]
Hmm, I forgot to tag it (thanks for the reminder), but the latest release is 0.5.8, and it was done this May: https://github.com/purcell/mmm-mode/commit/8aed53f9aec4bcb9faf5f2b080e863f51d775905

It should also hopefully make the config line everybody in that thread seems to be touting (`(setq syntax-ppss-table nil)`) unnecessary (that was issue #99).

Are you using some package system that pays attention to tags? 0.5.8 is in GNU ELPA now.

**Comment by AlexDaniel** [comment]
@dgutov I think I did check that I had 0.5.7, but I'm no longer sure and I'm questioning everything :) I'm currently using Doom Emacs.

Anyway, thanks for the tag!
