### ISSUE TITLE
rst-mode won't fill-paragraph?

### ISSUE THREAD

**Issue by ecoon** [purcell/mmm-mode#123]
I stumbled upon mmm-mode while trying to edit ReST comments inside a C++ source file, and was very excited because we use Sphynx and rst to document our C++ code, and not having to swap back and forth between major modes depending upon whether I'm editing documentation or editing code was very appealing.

After a few tries, I was able to create a subclass for rst-mode as a submode to c++-mode, and syntax highlighting and the gray background for ReST blocks seems to work perfectly.

Unfortunately, fill-paragraph does not.  And since indentation is a crucial part of ReST (particularly for lists, code blocks, definitions, etc), fill-paragraph is pretty much the only reason I really wanted mmm-mode to work.  I also tried org-mode instead of rst-mode, and that seems to work with fill-paragraph (but fills incorrectly for ReST -- I just wanted to confirm that the problem was not bigger than rst-mode).

Note that, if I swap between major modes for the full file, fill-paragraph works as expected.

Do you have suggests of how to start debugging/thinking about fixing this?  

My first guess was that rst-mode was capturing fill-paragraph and doing something weird, but it appears that there is no special rst-fill-paragraph or anything.

My second guess was that rst-mode's use of fill-paragraph relied upon variables that were getting lost in the c++-mode transition.  I noticed a bunch of variables are "saved" when you drop into c-mode, for instance.  So I tried adding a bunch of rst-mode variables to mmm-vars.el, e.g. `rst-indent-width` and other seemingly related things, but that didn't seem to change anything.

I'll fully admit, I'm not an elisp practitioner, so I'm not that familiar with debugging elisp.  I'm willing to try a few more things, but was hoping for any advice on why this might be failing or how to make this work.

Note, this is with emacs27 and both the ELPA release from 2020 and the current master of this repo.

**Comment by dgutov** [comment]
Do I understand it right that fill-paragraph doesn't work as expected when inside an rst-mode subregion? And work fine when it is "fully" the major mode of the buffer?

Then yes, it's probably affected by some variables that were set or unset.

In particular, `fill-paragraph-function` seems to fit the bill. Maybe there are others, I'm not an expert at that feature.

Try adding `fill-paragraph-function` to `mmm-save-local-variables`. Like this:

```el
(add-to-list 'mmm-save-local-variables 'fill-paragraph-function)
```

Maybe do that for `fill-paragraph-handle-comment` as well.

**Comment by ecoon** [comment]
Perfect, this sent me down the right path, thanks much.  I had to add a few more variables to get the right hooks in for auto-fill-mode, but this works now:

```
;; mmm-mode: rst in C++
(use-package mmm-mode
  :config
  (setq mmm-global-mode 'maybe)
  (setq mmm-parse-when-idle nil)
  (mmm-add-classes
   '((cpp-rst
      :submode rst-mode
      :front "/\\*!"
      :back "\\*/"
      :end-not-begin t)))
  (mmm-add-mode-ext-class 'c++-mode "\\.hh\\'" 'cpp-rst)
  (add-to-list 'mmm-save-local-variables '(fill-paragraph-function buffer (rst-mode)))
  (add-to-list 'mmm-save-local-variables '(fill-paragraph-handle-comment buffer (rst-mode)))
  (add-to-list 'mmm-save-local-variables '(adaptive-fill-function buffer (rst-mode)))
  (add-to-list 'mmm-save-local-variables '(indent-line-function buffer (rst-mode)))
  (add-to-list 'mmm-save-local-variables '(adaptive-fill-regexp buffer (rst-mode)))
  (add-to-list 'mmm-save-local-variables '(adaptive-fill-first-line-regexp buffer (rst-mode)))
)
```

I'm not sure I understand what needs to be saved.  Is it only things that would be "overwritten" or otherwise clash with the other major mode's value of that variable?  Or is it any variable that would be required in that mode? 

At any rate, thanks, this is working great now.

**Comment by ecoon** [comment]
I'm happy to submit a PR with these in mmm-vars.el if that would be of more general interest.  I'm not sure how much active development is happening or whether you want PRs at this point.

**Comment by dgutov** [comment]
> I'm not sure how much active development is happening or whether you want PRs at this point.

Sure, I'd be happy to have more appropriate vars added to that list.

**Comment by ecoon** [comment]
```
(use-package mmm-mode
  :ensure t
  :config
  (setq mmm-global-mode 'maybe)
  (setq mmm-parse-when-idle nil)
  (mmm-add-classes
   '((cpp-rst
      :submode rst-mode
      :front "/\\*!"
      :back "\\*/"
      :end-not-begin t)))
  (mmm-add-mode-ext-class 'c++-mode "\\.hh\\'" 'cpp-rst)
  (add-to-list 'mmm-save-local-variables 'fill-paragraph-function)
  (add-to-list 'mmm-save-local-variables 'fill-paragraph-handle-comment)
  (add-to-list 'mmm-save-local-variables 'adaptive-fill-function)
  (add-to-list 'mmm-save-local-variables 'adaptive-fill-regexp)
  (add-to-list 'mmm-save-local-variables 'adaptive-fill-first-line-regexp)
)
```

Sure, so that works as well, I guess I didn't need indent-line-function.  My thinking there was that the indent function (on e.g. a bullet list) would get called during a fill-paragraph call, but maybe not.

On the scope, I think I get it now -- I was thinking "global" vs "buffer" vs "region" was narrowing the scope of the effect, but I see what it is now -- effectively this is the scope over how often you would set that value, so "bigger is better" in this case.

I'd really only added that because I was thinking that restricting this to rst-mode was better than applying it to all modes.  Is it ever a bad thing to save "too much?"
