### ISSUE TITLE
is it possible to have an entire submode block begin at four spaces?

### ISSUE THREAD

**Issue by iambumblehead** [purcell/mmm-mode#124]
I tried using mmm-mode to highlight vue3 components. It looks and works near-perfect. If I could have the submode (web-mode) start at the 4-space position it would be perfect. Does anyone know how I might do this?

<img width="600" alt="Screen Shot 2022-07-25 at 5 51 56 PM" src="https://user-images.githubusercontent.com/2058705/180899308-8269de50-0749-4f70-b1b1-67a044ff0e88.png">

**Comment by iambumblehead** [comment]
if the opening tag is indented four spaces, the rest of the block follows the same indentation, which might be good enough for me

**Comment by iambumblehead** [comment]
this was "resolved" by downloading the web-mode sources and updating those

**Comment by dgutov** [comment]
I could also suggest `html-mode` as the simpler option for the submode.

But if `web-mode` works okay and brings some benefits, even better.
