### ISSUE TITLE
What is the Emacs minimum version?

### ISSUE THREAD

**Issue by snogge** [purcell/mmm-mode#127]
I cannot find any Package-Requires or any other mention of a minimum required Emacs version. 
There are some (not many) used functions/variables that are deprecated, but it is hard to fix them if there is no limit on the backward compatibility.

**Comment by dgutov** [comment]
Hi!

That was a benefit to a package that isn't changed too much: it keeps working in old Emacsen.

But I suppose we should clean up at some point. Maybe 24.4. Or 25.1?

@purcell what do you think?

**Comment by purcell** [comment]
> But I suppose we should clean up at some point. Maybe 24.4. Or 25.1?

I'd be fine with either, but we should make it explicit.

**Comment by dgutov** [comment]
Ok, let's make it 25.1, then.

**Comment by snogge** [comment]
You have commented on this before in #19 .
Is it OK to drop XEmacs support too?

**Comment by dgutov** [comment]
Yeah. This repo is upstream now, and, 9.5 years later, there is really no XEmacs anymore.
