### ISSUE TITLE
Ragel mode

### ISSUE THREAD

**Issue by timoc** [purcell/mmm-mode#38]
I created a primitive ragel mode: 
http://www.emacswiki.org/emacs/RagelMode

Ragel is a bit like bison mode or antlr mode, in that it is mixed in with other target languages. Can mmm-mode handle this? or should it be a mode on its own.

**Comment by dgutov** [comment]
This is very old, sorry for lack of better responses.

But a report like this should come with a reproduction scenario. Please feel free to add some details, if you want to reopen.
