### ISSUE TITLE
mmm-mode causes segfault

### ISSUE THREAD

**Issue by snogge** [purcell/mmm-mode#39]
This is probably related to issue #30.

Loading this file: http://git.yoctoproject.org/cgit/cgit.cgi/poky/plain/meta/classes/base.bbclass?h=daisy
in fundamental mode and then activating `mmm-mode` with this mmm-class:

```elisp
`(;;python functions starting with `def'
    (bitbake-python-def
      :submode python-mode
      :face bitbake-python-function-face
      :front "^def[[:blank:]]+"
      :include-front t
      :back ,(rx line-start (in graph))
      :include-back nil
      :back-offset -1)
```

will cause Emacs 24.3.1 to segfault when calling `mmm-parse-buffer` or sometimes by scrolling in the buffer or jumping straigh to the end.  I do not see this problem with mmm-mode 0.4.8 distributed with debian wheezy, but I do see it in 0.5.1 in debian jessie.  The bug is also in mmm-mode on MELPA.  

This is tested on Debian Jessie with Emacs 24.3+1-5.

**Comment by dgutov** [comment]
24.4 is in Debian Jessie now.
