### ISSUE TITLE
Incorrect ERB highlighting

### ISSUE THREAD

**Issue by ineu** [purcell/mmm-mode#42]
If an ERB code is present in the buffer, then HTML following it is parsed incorrectly, if it contains code in attributes. For example
**HTML/ERB only**
![first](https://cloud.githubusercontent.com/assets/24980/5772837/0fa21456-9d6a-11e4-8f8d-b834329e90b3.jpg)
Line 5 and further are highlighted correctly.

**HTML/ERB with ERB snippet at the beginning**
![second](https://cloud.githubusercontent.com/assets/24980/5772842/2fca0162-9d6a-11e4-8c07-52979ea2c68d.jpg)
Highlighting is broken for line 7 and further, but only if ERB snippets are embedded in the attributes.

**Comment by dgutov** [comment]
Do you use the configuration described in `mmm-erb.el`? You should.

**Comment by ineu** [comment]
Yes:
```elisp
(require 'mmm-auto)
(setq mmm-global-mode 'maybe)
(setq mmm-parse-when-idle t)

(mmm-add-mode-ext-class 'html-erb-mode "\\.html\\(\\.erb\\)?\\'" 'html-js)
(mmm-add-mode-ext-class 'html-erb-mode "\\.html\\(\\.erb\\)?\\'" 'html-css)
(mmm-add-mode-ext-class 'html-erb-mode "\\.html\\.erb\\'" 'erb)
(mmm-add-mode-ext-class 'html-erb-mode "\\.jst\\.ejs\\'" 'ejs)

```

**Comment by dgutov** [comment]
I guess you'll have to post your test file, then.

It works fine here with Emacs master and my test example.

**Comment by ineu** [comment]
I've found an issue, thank you.
I've tried using stable melpa (http://stable.melpa.org/) which builds packages from tagged revisions, and last tag for mmm is almost two years old. Switched back to melpa, it's fine now.
Though it would be good to have more recent tag, for those who would use stable mepla.

**Comment by dgutov** [comment]
Right, guess it's time for a new release.
