### ISSUE TITLE
Example use?

### ISSUE THREAD

**Issue by kaushalmodi** [purcell/mmm-mode#43]
Where can I find an example of a file in which mmm-mode is used? Can you create an example of org-mode sections embedded in a perl code?

It was not clear from the README file on how to implement this:

**Comment by purcell** [comment]
Take a look at https://github.com/purcell/mmm-mode/blob/master/mmm-mason.el for a fairly straightforward example.

**Comment by kaushalmodi** [comment]
From what I understand, [Mason](http://en.wikipedia.org/wiki/Mason_%28Perl%29) is written in Perl. So I was expecting your file to have chunks of code written in pure Perl. But I fail to see that. Probably I am misunderstanding the application of mmm-mode. Can this mode be a solution to a problem like [this](http://emacs.stackexchange.com/q/7568/115)?

**Comment by purcell** [comment]
That file is a definition for how `mmm-mode` should recognise regions in a (perl) mason template, and apply different major modes to those regions.

**Comment by purcell** [comment]
So no, I don't think `mmm-mode` is applicable to that question, because there's no `pod-mode` major mode to use for the `pod` regions, and `mmm-mode` is explicitly for Multiple Major Modes. :-)

**Comment by dgutov** [comment]
@kaushalmodi

> Can this mode be a solution to a problem like this?

It can be, but you'd probably be better off with a lighter-weight solution using plain `font-lock-keywords`. The `MATCHER` element can be a function, so you could check (in a variety of ways) that point is after `__END__`.

@purcell

> there's no pod-mode major mode to use for the pod regions

One could as well create it. But it would be more work, yeah.

**Comment by kaushalmodi** [comment]
Cool! Thanks for the replies.
