### ISSUE TITLE
markdown-mode inside mml-mode?

### ISSUE THREAD

**Issue by fauno** [purcell/mmm-mode#44]
hi, i'm trying to make the email body to be parsed as markdown-mode, but i'm having trouble configuring it.  the following snippet works for any *.mail file (just for testing purposes) but it doesn't when i create a new message:

```elisp
(require 'mmm-mode)
(require 'mmm-auto)

(mmm-add-classes
 '((mml-markdown
    :submode markdown-mode
    :face mmm-declaration-submode-face
    :front "^--text follows this line--$"
    :back "^-- $")))

(mmm-add-mode-ext-class 'mml-mode nil 'mml-markdown)
(mmm-add-mode-ext-class nil "\\.mail\\'" 'mml-markdown)
```

the idea is that between start of email body and signature i can use markdown-mode, and this works if i create a test.email file matching the front and back regexes, but it doesn't on mml-mode, any idea why this could be happening? thanks!

![mmm-mode working on test.mail](https://cloud.githubusercontent.com/assets/468204/5983098/bfddb82c-a8a8-11e4-917f-b704456bc22e.png)

![mmm-mode not working in mml-mode](https://cloud.githubusercontent.com/assets/468204/5983111/f47df902-a8a8-11e4-86c4-de73642996b0.png)

**Comment by dgutov** [comment]
I don't know, works for me if I replace `mml-mode` with `message-mode`. Are you sure your mail buffers are actually in `mml-mode`?

Another thing: `mmm-mode` doesn't automatically reparse buffers. So when you have a new message, you might have to press `C-c % C-b` to get the buffer reparsed after typing that closing part (`-- `). And also check that that line has a space at the end.

**Comment by fauno** [comment]
it works! i don't know why i was convinced it was mml-mode, thanks :)
