### ISSUE TITLE
Installing from elpa is not providing documentation.

### ISSUE THREAD

**Issue by jaseemabid** [purcell/mmm-mode#46]
I installed `MMM Mode version 0.5.2 by Michael Abraham Shulman` from melpa (mmm-mode-20150117.239)

**Comment by purcell** [comment]
Yes, the `mmm.texinfo` fails to build with `makeinfo` due to `version.texi` being missing. Hey @dgutov, should we just remove the inclusion of that file? I see you removed `version.texi` in December.

**Comment by dgutov** [comment]
@purcell I don't know, that might have been a mistake. But it builds fine on my machine.

See the discussion in #41.

**Comment by purcell** [comment]
MELPA doesn't use autogen/configure/make.

**Comment by dgutov** [comment]
But it builds `.texinfo` otherwise?

I don't see `version.texi` in Flycheck's repo. Maybe the correct solution is to build the `.info` file without it here, too.

**Comment by jaseemabid** [comment]
@purcell I could follow the readme and build the info file locally just fine. Maybe locally build info file should also be tracked due to melpa limitations.

**Comment by purcell** [comment]
> But it builds .texinfo otherwise?

Yes, it tries to, but then fails.

> I don't see version.texi in Flycheck's repo. Maybe the correct solution is to build the .info file without it here, too.

That would be ideal, I think.

**Comment by fedeinthemix** [comment]
I installed mmm-mode from Melpa and it is still missing the documentation.

I the downloaded the .texinfo and, with the command 'makeinfo mmm.texinfo', it fails to build. 
If I comment the directive for inclusion of the 'version.texi' file, the .info file is created (with warnings).

It would be very nice if this could be fixed so that people would get the documentation when installing with the recommended installation method. Several packages just put directly the '.info' and 'dir' files in the repo.

Thanks for the useful package!

**Comment by dgutov** [comment]
Sorry, I don't have the time to learn the Texinfo basics now. Someone else might need to submit the fix.

**Comment by fedeinthemix** [comment]
On Wed, Jun 17, 2015 at 1:18 PM, Dmitry Gutov <notifications@github.com>
wrote:

> Sorry, I don't have the time to learn the Texinfo basics now. Someone else
> might need to submit the fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/purcell/mmm-mode/issues/46#issuecomment-112759482>.
>
OK, the attached patch get rid of the need for version.texi, but the dates
and version number will have to be updated manually.

Hope this helps,
Fede

**Comment by dgutov** [comment]
The attachment didn't come through. Maybe make a pull request?

**Comment by fedeinthemix** [comment]
I'm not a GitHub user. What about copy/paste :-/

```
--- mmm.texinfo.orig    2015-06-17 14:09:45.931101614 +0200
+++ mmm.texinfo 2015-06-17 14:08:52.270505604 +0200
@@ -11,7 +11,11 @@
 * MMM-Mode: (mmm).                 Multiple Major Modes for Emacs
 @end direntry
 
-@include version.texi
+@c @include version.texi
+@set UPDATED 17 June 2015
+@set UPDATED-MONTH June 2015
+@set EDITION 0.5.2
+@set VERSION 0.5.2
 
 @ifinfo
 This is edition @value{EDITION} of the MMM Mode Manual, last updated
```
Hope this works.

**Comment by purcell** [comment]
Alternative would be checking in the latest generated `version.texi`, such that updating it could still be automated.

**Comment by dgutov** [comment]
@purcell You mean revert the fix for #41?

**Comment by purcell** [comment]
Yes, actually. I don't think it's a big deal if there are merge conflicts after running `make`. Another alternative still would be to stop referring to any versions in the generated docs... :-)

**Comment by dgutov** [comment]
> Another alternative still would be to stop referring to any versions in the generated docs... :-)

That might be fine, too. Do the other third-party packages omit the versions in their texinfo as well?

**Comment by purcell** [comment]
Not really sure, but in any case I'd say that the installed GNU info docs for a package are not the most reliable place to discover which version of the package is installed.

**Comment by dgutov** [comment]
I think the idea is that if you obtained the info file somehow, you know exactly which version is corresponds to. That might be particularly useful if it's been rendered to HTML and published to the web.

**Comment by fedeinthemix** [comment]
Looking at the timestamp of mmm.texinfo on GitHub, it appears that the file has not been edited for 13y. So, maybe the best solution would be to remove references to VERSION, EDITION and UPDATED.

**Comment by dgutov** [comment]
Very well.

**Comment by fedeinthemix** [comment]
Thanks! 

The package on MELPA now does include the .info file. The one on MELPA Stable however does not. Does it just need more time, or does it somehow need to be kicked?

**Comment by dgutov** [comment]
MELPA Stable need a new mmm-mode release and a corresponding tag.

**Comment by purcell** [comment]
Tagged 0.5.3. Should build in the next couple of hours.

**Comment by dgutov** [comment]
@purcell Could you do the release according to the Checklist, then?

**Comment by purcell** [comment]
Erk... can't do that right now, but will get to it. Now that 0.5.3 is tagged, we should probably just follow the checklist in order to release a 0.5.4. Next time I'll just keep my hands off... :-)

**Comment by purcell** [comment]
Alright, done for 0.5.4.

**Comment by purcell** [comment]
Turns out I can follow instructions after all.

**Comment by dgutov** [comment]
Thanks :)
