### ISSUE TITLE
question about incorrect indentation

### ISSUE THREAD

**Issue by L42y** [purcell/mmm-mode#47]
I use the following code to deal code with JSX chunk inside of JavaScript:

```emacs-lisp
(mmm-add-classes
 '((jsx
    :submode web-mode
    :face mmm-code-submode-face
    :front "\\((\\)[[:space:]\n]*<"
    :front-offset -1
    :back ">[[:space:]\n]*\\()\\)"
    :back-offset 1)))
(setq mmm-global-mode 'maybe
      mmm-parse-when-idle t)
(mmm-add-mode-ext-class 'js-mode "\\.js\\'" 'jsx)
(mmm-add-mode-ext-class 'js-mode "\\.jsx\\'" 'jsx)
```

I expect to get result like this:
![screen shot 2015-03-18 at 1 13 42 pm](https://cloud.githubusercontent.com/assets/284820/6703055/ad76350a-cd70-11e4-9290-de57a4553a53.png)

but instead I got result like this:
![screen shot 2015-03-18 at 1 15 29 pm](https://cloud.githubusercontent.com/assets/284820/6703072/e939bf58-cd70-11e4-84d9-b14f8bea74e4.png)

any idea how can I fix this indentation problem? thanks!

**Comment by dgutov** [comment]
That's the indentation `web-mode-indent-line` creates, apparently.

To make it care about the context, you can try wrapping it an in mmm-mode-aware indentation function. See `mmm-erb-indent-line` in `mmm-erb.el` for an example.

**Comment by L42y** [comment]
thanks! will try
