### ISSUE TITLE
"Not enabling jit-lock: it does not work in indirect buffer" message

### ISSUE THREAD

**Issue by soonhokong** [purcell/mmm-mode#51]
I'm using mmm-mode to display [Lua](http://www.lua.org/) code in [Lean](http://leanprover.github.io) buffers. Here is [the setting file](https://github.com/leanprover/lean/blob/master/src/emacs/lean-mmm-lua.el) that I'm using.

Since I switch to emacs-24.4, I have "Not enabling jit-lock: it does not work in indirect buffer" message whenever I open a Lean buffer. I check that this message goes away when I turn off mmm-mode for Lean buffer.

It seems that everything is still working and it's not harmful. I just want to make sure that this is really OK. Also, if there is a quick way to turn off the message, I want to know. Thank you!

**Comment by dgutov** [comment]
The message is harmless, and you're not doing anything wrong. We can get rid of it, though.

Glad to know you find mmm-mode useful for this case.

**Comment by soonhokong** [comment]
@dgutov, thank you. Does f5ea03a handle this warning?

**Comment by dgutov** [comment]
@soonhokong Yes. That's why it closed this issue.

**Comment by soonhokong** [comment]
Great. Thank you!

**Comment by Trevoke** [comment]
Hi,

I'm working on a minor-mode where I change the major mode to `sql-mode` and I see this message come up in the minibuffer. I'd like to prevent font-lock-mode from being enabled in the indirect buffer but I'm not quite sure how to do it. This is the function I'm currently using to create the indirect buffer:

```emacs-lisp
(defun sqlup-work-buffer ()
  "Returns and/or creates an indirect buffer based on current buffer and set
its major mode to sql-mode"
  (or sqlup-work-buffer
      (set (make-local-variable 'sqlup-work-buffer)
           (with-current-buffer (clone-indirect-buffer
                                 (generate-new-buffer-name
                                  (format "*sqlup-%s*" (buffer-name)))
                                 nil)
             (set (make-local-variable 'font-lock-support-mode) nil)
             (sql-mode)
             (current-buffer)))))
```

All help on the matter is appreciated, though of course I understand that this is very out of scope of this project :)

**Comment by dgutov** [comment]
@Trevoke First, you might want to use let-binding instead of `make-local-variable`, because changing the major mode erases the local variables.

Then, the best I can recommend so far is to put a `(debug)` statement inside `jit-lock-mode` and see where the investigation leads. Here, it indicates that the only source remaining of that message is from `font-lock-mode` being disabled.

**Comment by Trevoke** [comment]
Great, thank you for the advice!

**Comment by frankjonen** [comment]
Fresh install here. The error is still present. Any further ideas how to solve it?

**Comment by dgutov** [comment]
Try using Emacs 26, maybe. I don't see this message anymore (and it's not an error anyway).
