### ISSUE TITLE
"Wrong type argument: stringp, nil" on saving buffer that hasn't got parts of other major mode

### ISSUE THREAD

**Issue by vlatkoB** [purcell/mmm-mode#52]
Hi,

saving works without problems if buffer has parts of other mode (in this case, if Haskell module has Hamlet code).
However, when I try to save Haskell buffer without Hamlet code, minibuffer shows "Wrong type argument: stringp, nil"

This is config:
```
    (use-package mmm-auto)
    (use-package mmm-vars)
    (setq mmm-global-mode 'maybe)
    (mmm-add-classes
     '((hamlet-quasiquote
	  :submode hamlet-mode
	  :delimiter-mode nil
	  :front "\\[?hamlet|"
	  :back "|\\]")))
    (mmm-add-mode-ext-class 'haskell-mode nil 'hamlet-quasiquote)
```
This is truncated debugger output:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-width(nil)
  company-ghc--search-import-start()
  company-ghc--scan-impdecl()
  company-ghc-scan-modules()
  run-hooks(after-save-hook)
  basic-save-buffer()
  save-buffer(1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
```
Using "mmm-mode-20150610.1544" from Melpa.

Best regards,

vlatko

**Comment by dgutov** [comment]
Hi!

The error comes from `company-ghc`. @iquiw, do you think it'll be better fixed on this side, rather than on your side?

**Comment by iquiw** [comment]
@dgutov Sure.

I have never used mmm-mode though.
@vlatkoB Can you give me steps how to generate the error?

**Comment by iquiw** [comment]
> @dgutov Sure.

I meant I think it should be fixed in `company-ghc`.

**Comment by iquiw** [comment]
I could generate the error, but I have no idea how it happens.

[This](https://github.com/iquiw/company-ghc/blob/2e77fe370a53f48b596c7c1ebcb966f7fc6a407e/company-ghc.el#L277) `(match-string-no-properties 1)` returns nil only when mmm-mode is enabled (for the same buffer contents).

If `(match-string-no-properties 1)` is called just after `re-search-forward`, it returns non-nil result.

**Comment by dgutov** [comment]
@iquiw But it's not really called right after. `company-ghc--in-comment-p` is called first, and it calls `syntax-ppss`, and *that* may end up doing some searches, too.

I think you need to use `save-match-data` in `company-ghc--search-import-start`.

**Comment by vlatkoB** [comment]
@iquiw I see you can generate error. Do you still need steps and/or additional info?

**Comment by iquiw** [comment]
@dgutov Ah, I see. Thanks!

@vlatkoB No. I will do the fix using `save-match-data`.

**Comment by iquiw** [comment]
I pushed the fix.

**Comment by vlatkoB** [comment]
No more warning with this fix. Closing issue.

You guys are really fast. Only `17` hours for two different packages maintainers to find, agree and publish the fix. :+1:

**Comment by dgutov** [comment]
@vlatkoB Yup. Emacs makes it rather easy.

Thanks to you both.
