### ISSUE TITLE
Usage of delimiter-mode, front-face and back-face

### ISSUE THREAD

**Issue by ivan-m** [purcell/mmm-mode#53]
Apologies if this isn't a bug, but I've never (successfully) used mmm-mode before.

I'm trying to set it up so that pandoc-style YAML metadata blocks are recognised in markdown-mode.

This works well enough:

```
(mmm-add-classes
 '((pandoc-yaml
    :submode yaml-mode
    :front "^---\n"
    :back "^\\.\\.\\.$")))
```

(Ideally, I'd prefer to let the ending also be `---`, but that seems to cause it issues trying to determine if the `---` is starting or ending a yaml block.)

However, markdown-mode still keeps thinking that the starting `---` is either part of a header or a line marker and fontifying them thusly.  So I thought I could use either the `:delimiter-mode`, `:front-face` or `:back-face` settings to change how they are fontified, but even with `mmm-submode-decoration-level` set to `2` these settings don't seem to actually do anything (I've tried setting them to random modes and faces to no avail).

Is this the expected behaviour?  Or should I indeed be able to override the primary mode's face settings for the delimiters?

**Comment by dgutov** [comment]
Do you have an example file?

**Comment by ivan-m** [comment]
```markdown
---
title: A Title
author: A name
date: A date
...

# Hi

* This is a list

Random text

---
#  -*- mmm-classes: pandoc-yaml -*-
...
```

**Comment by ivan-m** [comment]
Actually, I've just realised that my mmm class above causes problems if I _do_ want to use exactly `---` as either part of a heading specification of a line marker, for example by adding this somewhere in the middle:

```markdown
Foo
---
```

Is there any way of stating that a region can't contain a delimiter?

**Comment by dgutov** [comment]
Thanks. This makes `front-face` and `back-face` work for me.

> Is there any way of stating that a region can't contain a delimiter?

Not sure what you mean by that: the problem is that some delimiters are not delimiters at all, right? But they're not inside any subregions.

If you can't avoid that ambiguity easily (via a style guideline, for instance), `:front` and `:back` can also be functions. You can write the `:front` function so that it checks the buffer contents after the delimiter, to see if it's in fact a delimiter.

**Comment by ivan-m** [comment]
That's fixed it, thanks!

Do you know of any examples I can look at for how to write such a function for `:front`?

**Comment by dgutov** [comment]
Actually, never mind. You just needed to specify `front-delim`. This does it:

```el
(mmm-add-classes
 '((pandoc-yaml
    :submode yaml-mode
    :front "^---\n"
    :front-delim 0
    :front-face error
    :back "^\\.\\.\\.$"
    :back-delim 0
    :back-face error)))
```

**Comment by ivan-m** [comment]
Do you mean instead of the patch? Or to prevent other usages of `---` acting as a starting delimiter?

**Comment by dgutov** [comment]
I've reverted the patch, since this behavior is documented in this description of front-delim and back-delim, in the `mmm-classes-alist` docstring.

> Do you know of any examples I can look at for how to write such a function for :front?

I can't find a good existing example of that. But generally, you'll have a `while` in there, and a `re-search-forward` call.
