### ISSUE TITLE
`:match-submode` passed escaped values

### ISSUE THREAD

**Issue by ivan-m** [purcell/mmm-mode#54]
I'm trying to use `:match-submode` to identify code blocks in Pandoc-flavoured markdown [code blocks](http://pandoc.org/README.html#fenced-code-blocks); i.e. something like this:

    ~~~~ {#mycode .haskell .numberLines startFrom="100"}
    qsort []     = []
    qsort (x:xs) = qsort (filter (< x) xs) ++ [x] ++
                   qsort (filter (>= x) xs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

where the sub-mode should be set as being in `haskell-mode`.

I've successfully managed to write the function for  `:match-submode` (it's a bit messy at the moment, but I can paste it here if you want) and tested it manually, but when I try and use it it doesn't seem to work.

After adding in some `(message ...)` calls, I've found that the reason it isn't working is that it seems that the result from `:front` is escaped, so that the value passed to my matching function becomes `{#mycode \.haskell \.numberLines startFrom="100"}` (note the extra `\` before the two `.`s).

I can work around this by explicitly adding an extra `\` to the regexp I use, but is this the expected behaviour?  (I couldn't find anything in the documentation and did start trying to dig through the code but it's way past time I tried getting some sleep.)

**Comment by dgutov** [comment]
Refer to the `mmm-classes-alist` docstring mentioned previously: `match-submode` is passed a  from from `front-form`. And:

> FRONT-FORM and BACK-FORM, if given, must supply a regexp used to match
the *actual* delimiter.  If they are strings, they are used as-is.  If
they are functions, they are called and must inspect the match data.
If they are lists, their `car' is taken as the delimiter.  The default
for both is \(regexp-quote \(match-string 0)).

This sounds like there's some intended purpose behind this choice (the result is used for matching later?); I haven't used it myself, and it's too complicated for me to get into right now.

**Comment by ivan-m** [comment]
Thanks for that; I hadn't realised it had the `regexp-quote` in there.
