### ISSUE TITLE
Highlight only region containting point

### ISSUE THREAD

**Issue by bersace** [purcell/mmm-mode#58]
Hi,

I'm using MMM to highligh python docstring as rst. ( https://github.com/bersace/dotemacs/blob/master/site-lisp/mmm-rst-python.el ) I would like to enable mode highlight only when my point is in the docstring. I don't known if that actually optimize Emacs on large file, what do you think of it ?

I'm not a lisp guru so i'm a bit lost in mmm code :) How could i tell mmm to switch fontlock only if user cursor is in region ?

Regards

**Comment by dgutov** [comment]
> I don't known if that actually optimize Emacs on large file, what do you think of it ?

I'm not sure it'll really improve performance: mmm-mode will still have to parse the whole buffer contents, even if it's not creating overlays and applying fontification to most subregions.

It would also need some internal changes: at the moment, the buffer contents are not re-fontified if you don't make any changes. With your proposal, we'll have to look around after each point movement and highlight the region it moved to. An maybe unhighlight the one it moved from? The amount of work might actually increase, if you're just reading and not typing.

IIRC, https://github.com/fgallina/multi-web-mode does what you describe (for the modes its supports). You could try it out and see how you like the result.

**Comment by bersace** [comment]
Yes, you right. That would be difficult, especially for bloc like docstrign that starts and stop with the same pattern : `"""`. Closing.

Thanks for the point !!
