### ISSUE TITLE
Modes are leaking

### ISSUE THREAD

**Issue by ihodes** [purcell/mmm-mode#60]
Notice if I have a single apostrophe above the code clock, the JS mode is highlighted like a string. Python appears to work. 

![](http://link.isaachodes.io/2k1i2W3M2G2T/Screen%20Shot%202016-03-19%20at%203.00.44%20AM.png)

If I have two (or any even number) above the JS block, it highlights correctly:

![](http://link.isaachodes.io/3s2R2e2v2Q3k/Screen%20Shot%202016-03-19%20at%203.02.00%20AM.png)

What can I do? My configuration is to the right of the problem in the screenshot:

```elisp
(use-package mmm-mode
  :init
  ;; from http://jblevins.org/log/mmm
  (defun mmm-markdown-auto-class (lang &optional submode)
  "Define a mmm-mode class for LANG in `markdown-mode' using SUBMODE.
   If SUBMODE is not provided, use `LANG-mode' by default."
  (let ((class (intern (concat "gfm-" lang)))
        (submode (or submode (intern (concat lang "-mode"))))
        (front (concat "^```" lang "[\n\r]+"))
        (back "^```$"))
    (mmm-add-classes (list (list class :submode submode :front front :back back)))
    (mmm-add-mode-ext-class 'gfm-mode nil class)))
  (mapc 'mmm-markdown-auto-class
        '("awk" "bibtex" "c" "cpp" "css" "html" "latex" "lisp" "elisp" "makefile"
          "markdown" "python" "r" "ruby" "sql" "stata" "xml" "clojure" "scheme"
          "python" "js" "ruby"))
  (mmm-markdown-auto-class "shell" 'shell-script-mode)
  (mmm-markdown-auto-class "ocaml" 'tuareg-mode)
  (mmm-markdown-auto-class "javascript" 'js-mode)
  (add-hook 'markdown-mode-hook 'mmm-mode)
  (setq mmm-parse-when-idle 't))
```

**Comment by dgutov** [comment]
Hi! What Emacs version is this?

I'm having trouble reproducing this exact behavior. But you could try this:

`M-x find-library`, enter `js`, press `RET`.

Then, in this file, find all calls to `(widen)`, and remove them. Then save, recompile and restart Emacs. Or, to try it out, just `M-x eval-buffer` in there, then switch to the Markdown buffer in question, and try to remove/add that apostrophe at the beginning.

Let me know if that changes anything.

**Comment by ihodes** [comment]
Emacs is 24.5.1. 

I can no longer reproduce this… I don't know if I'm happy or sad about this, but I'll go with happy :) 

Thanks for the help debugging, and sorry for the trouble. I'll come back to this issue with a better repro if it strikes again.
