### ISSUE TITLE
flycheck and js2-mode error when editing html file

### ISSUE THREAD

**Issue by futurist** [purcell/mmm-mode#62]
think below normal html file:

````
<!doctype html>
....
<body>
<script>
  var abc=1234;
</script>
````
the mode is MMM+JS2+Flycheck etc.

Flycheck has below error:

````
<!doctype html>
    1   2 error           Parsing error: Unexpected token < (javascript-eslint)
````
So flycheck checks javascript from first char, that is < char.

JS2 has below error:
````
Parse failed....
````

Also parsed from start of html file, which lead to fail.

Using `Muilti-web-mode` all work ok, but it's very slow and buggy.

If mmm-mode could solve this, that's perfect!

**Comment by dgutov** [comment]
`js2-mode` doesn't work with `mmm-mode`. Sorry. Use `js-mode`.
