### ISSUE TITLE
[Feature Request] improve html-erb-mode to support font face for current mode-special tags

### ISSUE THREAD

**Issue by zw963** [purcell/mmm-mode#64]
mmm-mode is fancy.
I hope if could add mode special tags highlight maybe more good.

set ```<%```??? ```%>``` special color as if `rhtml-mode`.
And for set ```<%=``` ??? ```%>``` use another color.
as did in rhtml-mode.

Thanks

**Comment by dgutov** [comment]
They're already using different faces with special colors, aren't they?

`mmm-code-submode-face` and `mmm-output-submode-face`.

**Comment by zw963** [comment]
Thanks, I could not found about any document about those face usage, from
`mmm-add-classes`, i think those face is for __code__ which between tags.
not, for special tags. is there any plan for tags special face? 
e.g.

(<%= and %> tags use special face difference from normal tag)
**<%=** render form **%>**

**Comment by dgutov** [comment]
Ah, I see what you mean. Here's an example of how you can do it, based on `mmm-erb.el`.

I'm not going to apply this patch (the extra highlighting seems unnecessary to me), but you can copy and change the declaration in your init script.

```diff
diff --git a/mmm-erb.el b/mmm-erb.el
index e1a4e3d..88032d4 100644
--- a/mmm-erb.el
+++ b/mmm-erb.el
@@ -66,6 +66,10 @@
         :match-face (("<%#" . mmm-comment-submode-face)
                      ("<%=" . mmm-output-submode-face)
                      ("<%" . mmm-code-submode-face))
+        :front-delim 0
+        :front-face custom-invalid
+        :back-delim 0
+        :back-face custom-invalid
         :insert ((?% erb-code nil @ "<%" @ " " _ " " @ "%>" @)
                  (?# erb-comment nil @ "<%#" @ " " _ " " @ "%>" @)
                  (?= erb-expression nil @ "<%=" @ " " _ " " @ "%>" @))

```

**Comment by zw963** [comment]
It seem like not render correct for me in some case.
![Screenshot at 2016-05-30 01:19:21.png](http://zw963.github.io/Screenshot at 2016-05-30 01:19:21.png)

Anywhy, i think this extra highlighting is not necessory too.

thanks.
