### ISSUE TITLE
Using a derived submode

### ISSUE THREAD

**Issue by am2605** [purcell/mmm-mode#67]
I had a requirement similar to #45 with regards to indenting of a submode but when I try and implement it I've having some problems

I've tried to do something similar to this, however when I use my derived "cfscript-mode" I lose the highlighting in my primary mode.

I've created a gist here that shows my mode and a sample file.  https://gist.github.com/am2605/ae81bac0daa789c9ce2ada03b2c844da

If I change the submode from cfscript-mode to js-mode I get the highlighting, so I'm not quite sure what I've done wrong.

Can anybody help please?

**Comment by dgutov** [comment]
That's because `mmm-save-local-variables` only has entries for `js--quick-match-re` and `js--quick-match-re-func` for `js-mode`. After you add similar ones for `cfscript-mode`, it all should work.

**Comment by am2605** [comment]
Thank you!
