### ISSUE TITLE
Updating the delimiters while typing in the submode

### ISSUE THREAD

**Issue by glynnforrest** [purcell/mmm-mode#70]
Given the following class:

```
(mmm-add-group
  'jinja2
  `((jinja2-variable
     :submode text-mode
     :face mmm-code-submode-face
     :front "{{ *"
     :back " *}}")))
```
And the text `{{'foo' ~ 'bar'}}`

The submode is highlighted. All good.

![screen shot 2017-05-15 at 20 50 07](https://cloud.githubusercontent.com/assets/578458/26076291/2daf326e-39b0-11e7-981f-bd5663aa325d.png)

Then I add a space, which has been included in the submode, not in the front delimiter.

![screen shot 2017-05-15 at 20 50 16](https://cloud.githubusercontent.com/assets/578458/26076318/45f61112-39b0-11e7-824b-7f24780092ae.png)

After running `mmm-parse-buffer`, I get my intended result:

![screen shot 2017-05-15 at 20 50 23](https://cloud.githubusercontent.com/assets/578458/26076336/5a4f1622-39b0-11e7-872e-fbf4f723444d.png)

Is there any way for the delimiter to get updated while typing?

I absolutely can't have the space go to the submode, since it crashes emacs. See https://github.com/glynnforrest/salt-mode/issues/3

Thanks!

**Comment by dgutov** [comment]
Please try:

```el
(setq mmm-parse-when-idle t)
```

**Comment by glynnforrest** [comment]
@dgutov this didn't work unfortunately, and I also tried different values for `mmm-idle-timer-delay`.

However, thanks to your help in the other thread, my underlying issue https://github.com/glynnforrest/salt-mode/issues/3 will be fixed with the next version of emacs.

I doubt live-updating of the delimiters will be worth the effort, especially when `mmm-parse-when-idle` will work for most cases.

**Comment by dgutov** [comment]
> this didn't work unfortunately

It works with the current Emacs master, then? That's good.
