### ISSUE TITLE
Setting global mmm-mode to "Always" breaks dotfile

### ISSUE THREAD

**Issue by dennismayr** [purcell/mmm-mode#77]
Hi,

Emacs + Spacemacs user here.
I noticed something strange:

I tried to `customize-group` `mmm-mode` and set the global option as _always on_.
After relaunching Emacs, I'm greeted with the "pick your editing style" dialog, as if I were configuring it for the first time. It's only fixed by removing the `mmm-mode` toggle in the dotfile.

Perhaps it's a Spacemacs problem, but I need to ask if this problem has been observed using plain Emacs. If so, please close this issue.

**Comment by dgutov** [comment]
> I need to ask if this problem has been observed using plain Emacs

That's what we like to know. Do you see it in plain Emacs?

The phrase "pick your editing style" doesn't appear in mmm-mode sources, though. Or in core Emacs.

**Comment by dennismayr** [comment]
Thanks for your input; then it's a spacemacs issue, I'll ask the community.

**Comment by syl20bnr** [comment]
Spacemacs lazy load packages, it seems to be related with lazy loading. 

Error in Spacemacs is:

```
(Spacemacs) Error in dotspacemacs/emacs-custom-settings: Cannot open load file: No such file or directory, mmm-mode
```

Should global mode be handled differently with a special function to enable it ?

**Comment by syl20bnr** [comment]
Nevermind, seems to happen even when I explicitly require the feature ;-)

**Comment by dgutov** [comment]
> Should global mode be handled differently with a special function to enable it ?

Sorry, differently from what?

> even when I explicitly require the feature

`mmm-mode.el` is a file present in this package. When this package's installation directory is inside `load-path`, `(require 'mmm-mode)` should work just fine.
