### ISSUE TITLE
jit-lock error when visual-line mode enabled in markdown-mode

### ISSUE THREAD

**Issue by ztlevi** [purcell/mmm-mode#78]
The problem is I got `Not enabling jit-lock: it does not work in indirect buffer` error when `visual-line-mode` enabled in `markdown-mode`(by adding a hook to markdown-mode). That's the only config I changed and the error appears instantly, so I assume that's the problem.

```
#### System Info :computer:
- OS: darwin
- Emacs: 25.3.3
- Graphic display: t
- Completion: ivy
```

**Comment by frankjonen** [comment]
That sounds close to my issue as well.
