### ISSUE TITLE
Deal with non-FSF assigned files

### ISSUE THREAD

**Issue by dgutov** [purcell/mmm-mode#81]
Now that we have copyright assignment from the two principal authors, we can do the move to GNU ELPA.

Unfortunately, what was not apparent from the commit history when I did the brief research, there are two files that are authored by other people.

1. `mmm-rpm.el`. It's very small (and appears to satisfy the FSF condition for a "small change"), but it's wholly authored by one person, so it's hard to reasonably change the copyright string at the beginning to "Free Software Foundation", which is what ELPA scripts seemingly expect. We can try to work around it, but can probably just delete the file, because it's never come up on our issue tracker, and when I tried it out, the syntax highlighting broke (apparently because `rpm-spec-mode` doesn't use `define-derived-mode`). So I was going to submit a patch to that effect, but that repository seems unmaitained, with several PRs just laying around.

We can delete it, and bring back in some form if anybody asks.

2. `mmm-noweb.el`. It has come up in our issue tracker, and the file is much larger. Unfortunately, the author has passed away: https://docs.freebsd.org/cgi/getmsg.cgi?fetch=1432367+0+/usr/local/www/mailindex/archive/2011/freebsd-ports-bugs/20110213.freebsd-ports-bugs.

The solution is probably to extract it to a separate package. @purcell Would you like to do that? Also: any other thoughts?

I've posted to emacs-devel about this, but we can probably guess the answer in advance.

**Comment by purcell** [comment]
I'm fine with removing `mmm-rpm.el`

I can't really comment on `mmm-noweb.el` -- I don't particularly remember our previous discussion about moving `mmm-mode` to GNU ELPA. I mean, it's absolutely fine with me, but I don't have time right now to do extra work to make that happen. If you wanted to move the rest of the package there, without `mmm-noweb.el`, that would be okay. Someone can pick up and host `mmm-noweb.el` later if desired.

**Comment by dgutov** [comment]
>  don't particularly remember our previous discussion about moving mmm-mode to GNU ELPA

Not much of a discussion (I never expected anybody to object), but you can search your inbox for "Adding mmm-mode to GNU ELPA and copyright assignments", I Cc'd your email at sanityinc.com.

The response from emacs-devel has been pretty positive so far, so I'll probably push the whole package as-is, and then extract mmm-noweb if somebody seriously objects to its presence here.

**Comment by purcell** [comment]
Sounds good - and yes, I vaguely remember the email discussion! Thanks for doing this. When the time comes to remove this repo, let me know.

**Comment by dgutov** [comment]
Not sure if we're ever going to remove this repos: even if most developments occurs there, syncing shouldn't be too much trouble. And I vastly prefer GitHub's bug tracker.

**Comment by dgutov** [comment]
Pushed to ELPA :sunny:

**Comment by purcell** [comment]
Great, thanks. I've removed the MELPA recipe and noted in the README that ELPA (rather than MELPA) is now the preferred installation source.

**Comment by purcell** [comment]
(I guess I'll keep this repo here for now?)

**Comment by dgutov** [comment]
Well, um, company and js2-mode are also in GNU ELPA, but still have their MELPA recipes, don't they?

Publishing in MELPA Stable is not really necessary, but some users might see it helpful to install the most recent build from master (using MELPA). Unless you really want to remove this repository :-)

**Comment by purcell** [comment]
I haven't worked with ELPA previously, so I wasn't sure if publishing this there had involved creating a new repo elsewhere, perhaps Savananh. If not, then of course I'm happy to keep this one! :-)

I guess I'll leave the MELPA recipe deleted for now and see if anyone notices.

**Comment by dgutov** [comment]
Nah, with the current config it's just `git pull/push elpa externals/mmm-mode`.

> I guess I'll leave the MELPA recipe deleted for now and see if anyone notices.

Sure. Guess it'll only become important if the development really picks up anyway.

**Comment by dgutov** [comment]
@purcell Well, I noticed now: https://github.com/purcell/mmm-mode/issues/102#issuecomment-633167923

:confounded:

**Comment by purcell** [comment]
Shall we re-add it, @dgutov?

**Comment by dgutov** [comment]
@purcell That would help.

Will you do the `git revert`, or do we need a new recipe?

**Comment by purcell** [comment]
I've done it, should get included in the next build cycle.

**Comment by dgutov** [comment]
Thanks!
