### ISSUE TITLE
un-namespaced cl functions

### ISSUE THREAD

**Issue by nholiphant** [purcell/mmm-mode#83]
In order to make mmm-mode work properly for me I have to replace mapcan, caddr and cadddr with cl-mapcan, cl-caddr and cl-cadddr respectively. It seems cl-mapcan, cl-caddr and cl-cadddr are not namespaced properly in the package.

**Comment by dgutov** [comment]
Have you updated to 0.5.6? Should be fixed there.

**Comment by nholiphant** [comment]
Thanks, will do.

**Comment by dgutov** [comment]
Should be fine now.
