### ISSUE TITLE
0.5.5: doesn't work with xemacs

### ISSUE THREAD

**Issue by az143** [purcell/mmm-mode#84]
xemacs (21.4.24) has a syntax.el but that module doesn't have any of the capabilities of gnu emacs' syntax.el, ie. no syntax-begin-function and none of the syntax-ppss-* stuff.

maybe it's time to drop the claim that mmm-mode works with xemacs?

**Comment by dgutov** [comment]
Hi!

Could you clarify how it doesn't work exactly? Do you get an error? We do handle the syntax- stuff, but it's mostly optional.

And also, are you an XEmacs user, or did you just try it out out of curiosity?

**Comment by az143** [comment]
On Thu, 29 Mar 2018 07:17:24 +0000, Dmitry Gutov writes:
>Could you clarify how it doesn't work exactly?

first, mmm-mode doesn't load because xemacs has cl, not cl-lib.
that's not too hard to fix; cl-lib can be added without much hassle,
i did try that but i got only a little further.

second, mmm-mode doesn't start because syntax-begin-function
(mmm-mode.el and mmm-region.el) does not exist in xemacs.

i see that the unreleased code in the repo only uses that in mmm-mode.el,
and behind a boundp conditional. that's however not the case in 0.5.5.

i tried retrofitting that boundp setup, again getting just a bit further.

third, mmm-mode doesn't start because the function
syntax-ppss-flush-cache does not exist in xemacs (used by mmm-class.el)
nor do syntax-ppss-cache or syntax-ppss-last (mmm-region.el).

xemacs comes with a syntax.el, but that syntax.el doesn't have any 
of the ppss stuff, and as both gnu emacs' and xemacs syntax.el 
(provide 'syntax) i gave up; gnu emacs' syntax.el doesn't seem easily
loadable into an xemacs.

>Do you get an error? We do handle the syntax- stuff, but it's mostly optional.

yes. Cannot open load file: cl-lib, symbol's definition is void
for syntax-begin-function, and symbol's definition is void for syntax-ppss-flush-cache.

>And also, are you an XEmacs user, or did you just try it out out of
>curiosity?

neither. i'm the maintainer of the mmm-mode package in debian, and i was
informed that 0.5.5 doesn't byte-compile or work with xemacs (see
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893930).

regards
az


-- 
Alexander Zangerl + GPG Key 2FCCF66BB963BD5F + http://snafu.priv.at/
perl -le '$b=1; print $a+=$b while print $b+=$a'

**Comment by dgutov** [comment]
> cl-lib can be added without much hassle, i did try that but i got only a little further

Yup. If XEmacs has a more-or-less functioning cl, cl-lib from GNU ELPA should delegate fine to it.

> i see that the unreleased code in the repo only uses that in mmm-mode.el, and behind a boundp conditional. that's however not the case in 0.5.5

Why unreleased? 0.5.6 has been out for about a week now. So you can consider that item fixed there.

> syntax-ppss-flush-cache does not exist in xemacs (used by mmm-class.el)

Does this help?

```diff
diff --git a/mmm-class.el b/mmm-class.el
index 6b7d604..d745519 100644
--- a/mmm-class.el
+++ b/mmm-class.el
@@ -115,8 +115,10 @@ and interactive history."
   (mmm-clear-overlays start stop 'strict)
   (mmm-apply-classes (mmm-get-all-classes t) :start start :stop stop)
   (mmm-update-submode-region)
-  (syntax-ppss-flush-cache start)
-  (syntax-propertize stop)
+  ;; Try to continue supporting XEmacs for a while.
+  (when (fboundp 'syntax-propertize)
+    (syntax-ppss-flush-cache start)
+    (syntax-propertize stop))
   (mmm-refontify-maybe start stop))
 
 ;;}}}
```

> nor do syntax-ppss-cache or syntax-ppss-last (mmm-region.el)

Those are just dynamic variable bindings. They shouldn't break anything by themselves.

> neither. i'm the maintainer of the mmm-mode package in debian

Cool. But the reporter probably is an XEmacs user, though?

I'm asking because AFAIK XEmacs development has (almost?) stopped, and all existing users have been advised to migrate. I'm also not sure if the new mmm-mode version actually improves something for XEmacs users. And the vaguely planned further changes might have to finally, really make it incompatible, because they'll rely on syntax.el.

So we can try to preserve compatibility for a little while longer, but I wonder if XEmacs users shouldn't just be directed to use 0.5.4 (if it is, in fact, compatible, I haven't checked).

**Comment by az143** [comment]
sorry for the long delay - i've been a bit too busy...

On Sat, 31 Mar 2018 21:34:40 +0000, Dmitry Gutov writes:
>Why unreleased? 0.5.6 has been out for about a week now. So you can consider th
>at item fixed there.

there are no 0.5.6 release files on github, and no release tag either.

>Does this help?

yes, thank you. together with adding

;; xemacs' syntax.el doesn't have syntax-begin-function
(if (featurep 'xemacs)
		(defvar syntax-begin-function nil))

to mmm-compat your patch makes mmm-mode work on xemacs21.

regards
az


-- 
Alexander Zangerl + GPG Key 2FCCF66BB963BD5F + http://snafu.priv.at/
Q. How do you solve bus problems?
A. Shoot the driver.

**Comment by az143** [comment]
On Sun, 08 Apr 2018 13:23:43 -0700, Dmitry Gutov writes:
>> (if (featurep 'xemacs) (defvar syntax-begin-function nil))
>
>I'm not sure I understand how that's necessary.

it's necessary for 0.5.5, not for master/0.5.6.

regards
az


-- 
Alexander Zangerl + GPG Key 2FCCF66BB963BD5F + http://snafu.priv.at/
How do I set my LaserPrinter to "Stun"?!

**Comment by dgutov** [comment]
Should be fine now, then.
