### ISSUE TITLE
0.5.7 mmm-parse-buffer does not work

### ISSUE THREAD

**Issue by pmcvay** [purcell/mmm-mode#88]
Running mmm-parse-buffer in the latest release gives a `Args out of range: #<buffer buffer.php>, 0, 1`

**Comment by dgutov** [comment]
What do you mean by "running"?

Calling `M-x mmm-parse-buffer` works for me.

**Comment by pmcvay** [comment]
For any combined php/html/js file I have, when running `M-x mmm-parse-buffer` exits with the error I showed in the first post. My mmm-mode setup is pretty basic just
`(require 'mmm-mode)
(setq mmm-global-mode t)
(mmm-add-mode-ext-class 'html-mode "\\.php$" 'html-php)
(mmm-add-mode-ext-class 'html-mode "\\.php$" 'html-js)`

**Comment by dgutov** [comment]
Can you try `M-x toggle-debug-on-error` first, and show the resulting backtrace?

**Comment by pmcvay** [comment]
Sure. After toggling it on, I get `Not enabling jit-lock: it does not work in indirect buffer` error. No backtrace pops up, but two blank mmm-temp-buffers are created

**Comment by dgutov** [comment]
@pmcvay So `M-x mmm-parse-buffer` started working? Or silently failing without an error?
