### ISSUE TITLE
"a buffer" should be "one buffer"

### ISSUE THREAD

**Issue by re-mx** [purcell/mmm-mode#89]
Hello:

See:
https://github.com/purcell/mmm-mode/blob/ff0b214f27d5dddeb856acb4216e77a864dcc0b2/mmm-mode.el#L1

I don't know English very well.
But I think "one" should mean "the same buffer" more than "a".

I don't know what the side effects of this change are, so I didn't submit the PR. Sorry.

Thanks.

**Comment by tim-teufel** [comment]
Well, consider a famous novel by Jerome K. Jerome named [Three Men in a Boat](https://en.wikipedia.org/wiki/Three_Men_in_a_Boat). Of course, it means "in the same boat".
That line is fine.

**Comment by dgutov** [comment]
Yup!

**Comment by re-mx** [comment]
Thanks.
