### ISSUE TITLE
Multimode with leading comments.

### ISSUE THREAD

**Issue by HugoNikanor** [purcell/mmm-mode#90]
I'm trying to get MMM-mode working with leading comment characters.
I currently have

```
(mmm-add-classes
 '((lisp-texinfo-comments
    :submode texinfo-mode
    :front "^;+"
    :back "^[^;]"
    :include-front t
    :include-back nil
    )))
```

in my config. This matches a group of lines all starting with semicolons (comment character) fine.

However; I would like to auto-insert the comment markers whenever I hit a new line. Is this somehow possible?

**Comment by dgutov** [comment]
With a custom hook or a separate mode. I think it's beyond the scope of mmm-mode (although I could be persuaded otherwise with a clean enough patch).
