### ISSUE TITLE
sql-mode submode of xml-mode font face

### ISSUE THREAD

**Issue by javierecf** [purcell/mmm-mode#91]
So i read another issue here that follows an approach to get sql-mode working inside ruby heredocs, but I'm having trouble implementing the same method to get sql-mode working inside xml-mode

this is my approach so far:

 

> 

(require 'mmm-mode)
(require 'mmm-auto)
(setq xml-sql-mmm-submode-enabled nil)
(defun xml-sql-mmm-submode ()
  "Provides a very minimal embedding of SQL in XML, via mmm-mode."
 (interactive)
  (when (not xml-sql-mmm-submode-enabled)
    (set-face-background 'mmm-default-submode-face nil)
    (mmm-add-classes
     '((embedded-sql
        :submode sql-mode
		:front "<[\\(Query\\)][^>]*>"
        :back "[ \t]*</Query>"
        ;:front "$\\(sql\\|query\\) = \""
        ;:back "\";"
        :face mmm-code-submode-face)))
    (mmm-add-mode-ext-class 'xml-mode "\\.xml" 'embedded-sql)
    (setq xml-sql-mmm-submode-enabled t)))

> 

And example of xml file would be
`
<Root>
<Query ID="myquery">
select * from table
</Query>
</Root>
`

but after running the functions, even with no errors showing up, the syntax highlighting of colors don't change at all in the XML buffer, is there any way to debug this? or maybe I'm missing something in the mmm-mode configuration?

**Comment by javierecf** [comment]
Got it working by adding 
(require 'nxml-mode)
(require 'sql) and changing xml-mode to nxml-mode in the code

**Comment by dgutov** [comment]
Sounds like you had associated `nxml-mode` with `.xml` files.

For this to work, you need to be using the major mode in question like you do now.
