### ISSUE TITLE
ess and mmm 

### ISSUE THREAD

**Issue by bernardomae** [purcell/mmm-mode#93]
Hello, 
I cannot get mmm to work an R script in ess-mode (emacs 25.2.2). I want to highlight some SQL code inside an R code. 
When I try to activate the mmm-mode (M-x mmm-mode RET) I get the following message:
customize-alist is not specified, nor ess-local-customize-alist is set
I added the following to my init file (~/.emacs.d/init.el) , also I get no message using --debug-init.
Here below what I added to the init file
Thanks a lot
best
Bernardo

(require 'mmm-mode)
(mmm-add-group
     'sql-in-ess
     '(
             (sql-query
                    :submode sql-mode
                    :face WHATEVERYOUWANT
                    :front "#SQL_QUERY>"
                    :back "#<SQL_QUERY")))
(add-to-list 'mmm-mode-ext-classes-alist '(ess-mode nil sql-in-ess))

**Comment by vspinu** [comment]
@bernardomae Is this a common mode? There are a lot of R specific multi-modes defined in [poly-R](https://github.com/polymode/poly-R/). Please open an issue there if you want help with this.

**Comment by dgutov** [comment]
Polymode might be a good choice, but as for this specific use case, could you try it again after `M-x toggle-debug-on-error`?

And you shouldn't have to `M-x mmm-mode`, opening a file in `ess-mode` should do the trick.

One more thing: I recommend you replace the first line with

```emacs
(require 'mmm-defaults)
```

**Comment by dgutov** [comment]
Oh well.
