### ISSUE TITLE
Can't install with MELPA

### ISSUE THREAD

**Issue by bipsen** [purcell/mmm-mode#98]
When I try to install from MELPA i get: 

`package-install-from-archive: https://elpa.gnu.org/packages/mmm-mode-0.5.7.tar: Bad Request`

What should I do?

**Comment by bipsen** [comment]
I got it to work with `package-install mmm-mode`.

**Comment by purcell** [comment]
Yeah, GNU ELPA has been giving me a bunch of "Bad Request" errors recently. This isn't related to MELPA, so I'm going to close this issue.
